baseURL = 'https://yellow-limit-4629.on.fleek.co/'
languageCode = 'en-us'
title = 'Eldms Blog'
theme = 'hugo-theme-tokiwa'

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "AboutMe"
    weight = 1
    identifier = "posts"
    url = "/posts/Intro"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "CS 381 Meta Signs Networks Presentation PPTX"
    url = "https://storageapi.fleek.co/1200202c-a1be-4b4b-83fe-43b3418e21b8-bucket/CS 381 NETWORKS PROJECT PRESENTATION.pptx"
    weight = 3
  [[menu.main]]
    name = "CS 372 Meta Signs Mobile App Presentation PPTX"
    url = "https://storageapi.fleek.co/1200202c-a1be-4b4b-83fe-43b3418e21b8-bucket/MetaSignsMobileCS372.pptx"
    weight = 3

[social]
reactjs = "https://yellow-wind-7477.on.fleek.co/"
vuejs = "https://crimson-cake-5360.on.fleek.co/"
linkedin = "https://www.linkedin.com/in/ethan-moore-eldm/"
github="https://github.com/eldm-ethanmoore"
twitter="https://twitter.com/eldm2350"
mail = "mailto:eldm2350@protonmail.com"
